### ISSUE TITLE
[Bug]: Error console

### ISSUE THREAD

**Issue by JellyBubb1e** [EvenMoreFish/EvenMoreFish#436]
### What happened?

The console is full of errors.

### Version

1.7.3

### Development Version

1.7.3#114

### Server Version

leaf-1.21.1.jar：1.21.1-DEV-d233f6b

### Java Version

21

### Relevant log output

```shell
[16:16:30] [Server thread/ERROR]: Could not pass event PlayerFishEvent to EvenMoreFish v1.7.3
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at even-more-fish-1.7.3-114.jar/com.oheers.fish.baits.BaitNBTManager.randomBaitApplication(BaitNBTManager.java:254) ~[even-more-fish-1.7.3-114.jar:?]
	at even-more-fish-1.7.3-114.jar/com.oheers.fish.fishing.FishingProcessor.getFish(FishingProcessor.java:168) ~[even-more-fish-1.7.3-114.jar:?]
	at even-more-fish-1.7.3-114.jar/com.oheers.fish.fishing.FishingProcessor.process(FishingProcessor.java:71) ~[even-more-fish-1.7.3-114.jar:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:39) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:65) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:543) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:33) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.world.item.ItemStack.use(ItemStack.java:605) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:489) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2122) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1553) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1531) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1524) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1482) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1489) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1336) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.1.jar:1.21.1-DEV-d233f6b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by noaskers** [comment]
Try to update to lates dev#build!
